### ISSUE TITLE
Transfer to daily-bruin, and Dockerize

### ISSUE THREAD

**Issue by hongee** [nbedi/lyst#4]
Hi @nbedi !

I'm one of the new assistant online editors for the Daily Bruin, and we're looking to consolidate our web resources into something more manageable using Docker. We're of course hoping to dockerize lyst too, as its currently running in a VPS of its own. To get things started, we're wondering if you're cool with transferring this repo to the daily-bruin organisation so it's a little easier to work with? If you've got any ideas or have any concerns about the whole process we are also definitely keen on discussing further! :)

**Comment by nbedi** [comment]
Hey @hongee, sorry meant to respond sooner. Yup I'll transfer this right over. Codebase is a bit of a mess if I remember correctly, I apologize ahead of time for that if you try to refactor or build an alternative. If you do refactor/build an alternative, let me know, there's some interesting stuff going on in lyst that you may need to know about.

**Comment by hongee** [comment]
Thanks so much @nbedi! We're a little short on manpower to work on this in the short term but we'll definitely want to look at this again in the future! Do also let us know if you're ever near the area :) I'm sure there are tons of people in DB who will be very interested to learn and hear about your experience on data journalism!
